name: R-CMD-check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  R-CMD-check:
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest, r: release, args: 'c("--as-cran")', build_args: "character()"}
          - {os: macos-latest, r: release, args: 'c("--as-cran", "--no-manual")', build_args: 'c("--no-manual")'}
          - {os: windows-latest, r: release, args: 'c("--as-cran", "--no-manual")', build_args: 'c("--no-manual")'}
          - {os: ubuntu-latest, r: devel, args: 'c("--as-cran", "--no-manual")', build_args: 'c("--no-manual")'}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-tinytex@v2
        if: matrix.config.build_args == 'character()'

      - name: Install LaTeX font packages
        if: matrix.config.build_args == 'character()'
        run: tlmgr install courier psnfss

      - name: Install HTML Tidy
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y tidy

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, any::testthat
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          args: ${{ matrix.config.args }}
          build_args: ${{ matrix.config.build_args }}
